import Head from "next/head";
import Image from "next/image";
import Button from "@/components/ui/Button";

import styles from "@/styles/Home.module.css";

import ParticipantForm from "../components/inputs/ParticipantForm";
import Header from "../components/layout/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header home={true} />
      {/* <Image
        className={styles.heroImage}
        src="/assets/images/pride_flags.jpg"
        width={1200}
        height={1200}
        alt="pride flag"
      /> */}
      {/* <div className={styles.btnContainer}>
        <Button link="/participants">
          <span>All Participants</span>
        </Button>
      </div>
      <div className={styles.welcomeContainer}>
        <div className={styles.welcomeTextContainer}>
          <h1 className={styles.welcomeText}>
            <span>Welcome to</span>
            <span>Queer</span>
            <span>speed dating</span>
          </h1>
        </div>
        <ParticipantForm />
      </div> */}
    </>
  );
}
