import Head from "next/head";
import Image from "next/image";

import styles from "@/styles/Home.module.css";

import ParticipantRegistration from "../components/inputs/ParticipantRegistration";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <Image
          className={styles.heroImage}
          src="/assets/images/pride_flags.jpg"
          width={1200}
          height={1200}
        /> */}
        <ParticipantRegistration />
      </main>
    </>
  );
}
